# Generated by Django 4.0 on 2023-08-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choix',
            old_name='question',
            new_name='questions',
        ),
    ]
